countries:
  - USA
  - Canada
  - Mexico
  - Brazil
  - Argentina
  - Chile
  - Colombia
  - Peru
  - United Kingdom
  - France
  - Germany
  - Italy
  - Spain
  - Netherlands
  - Switzerland
  - Austria
  - Japan
  - South Korea
  - China
  - India
  - Thailand
  - Singapore
  - Malaysia
  - Indonesia
  - Australia
  - New Zealand
  - South Africa
  - Egypt
  - Morocco
  - Turkey
  - Russia
  - Poland
  - Sweden
  - Norway
  - Denmark
  - Finland
  - Greece
  - Portugal
  - Ireland
  - Belgium

states:
  USA:
    - Alabama
    - Alaska
    - Arizona
    - Arkansas
    - California
    - Colorado
    - Connecticut
    - Delaware
    - Florida
    - Georgia
    - Hawaii
    - Idaho
    - Illinois
    - Indiana
    - Iowa
    - Kansas
    - Kentucky
    - Louisiana
    - Maine
    - Maryland
    - Massachusetts
    - Michigan
    - Minnesota
    - Mississippi
    - Missouri
    - Montana
    - Nebraska
    - Nevada
    - New Hampshire
    - New Jersey
    - New Mexico
    - New York
    - North Carolina
    - North Dakota
    - Ohio
    - Oklahoma
    - Oregon
    - Pennsylvania
    - Rhode Island
    - South Carolina
    - South Dakota
    - Tennessee
    - Texas
    - Utah
    - Vermont
    - Virginia
    - Washington
    - West Virginia
    - Wisconsin
    - Wyoming

  CANADA:
    - Alberta
    - British Columbia
    - Manitoba
    - New Brunswick
    - Newfoundland and Labrador
    - Northwest Territories
    - Nova Scotia
    - Nunavut
    - Ontario
    - Prince Edward Island
    - Quebec
    - Saskatchewan
    - Yukon

  BRAZIL:
    - Acre
    - Alagoas
    - Amapá
    - Amazonas
    - Bahia
    - Ceará
    - Distrito Federal
    - Espírito Santo
    - Goiás
    - Maranhão
    - Mato Grosso
    - Mato Grosso do Sul
    - Minas Gerais
    - Pará
    - Paraíba
    - Paraná
    - Pernambuco
    - Piauí
    - Rio de Janeiro
    - Rio Grande do Norte
    - Rio Grande do Sul
    - Rondônia
    - Roraima
    - Santa Catarina
    - São Paulo
    - Sergipe
    - Tocantins

# Default selections for better UX
defaults:
  origin_country: Brazil
  origin_state:
    USA: California
    Canada: Ontario
    Brazil: São Paulo
  destination_country: USA
  destination_state:
    USA: New York
    Canada: Ontario
    Brazil: Rio de Janeiro
